/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppPenaltiesRouteImport } from './routes/_app.penalties'
import { Route as AppPayrollRouteImport } from './routes/_app.payroll'
import { Route as AppIncentivesRouteImport } from './routes/_app.incentives'
import { Route as AppEmployeesRouteImport } from './routes/_app.employees'
import { Route as AppBonusesRouteImport } from './routes/_app.bonuses'
import { Route as AppAttendanceRouteImport } from './routes/_app.attendance'
import { Route as AppAdvancesRouteImport } from './routes/_app.advances'

const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPenaltiesRoute = AppPenaltiesRouteImport.update({
  id: '/penalties',
  path: '/penalties',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollRoute = AppPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppIncentivesRoute = AppIncentivesRouteImport.update({
  id: '/incentives',
  path: '/incentives',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppBonusesRoute = AppBonusesRouteImport.update({
  id: '/bonuses',
  path: '/bonuses',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAdvancesRoute = AppAdvancesRouteImport.update({
  id: '/advances',
  path: '/advances',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/unlock': typeof UnlockRoute
  '/advances': typeof AppAdvancesRoute
  '/attendance': typeof AppAttendanceRoute
  '/bonuses': typeof AppBonusesRoute
  '/employees': typeof AppEmployeesRoute
  '/incentives': typeof AppIncentivesRoute
  '/payroll': typeof AppPayrollRoute
  '/penalties': typeof AppPenaltiesRoute
}
export interface FileRoutesByTo {
  '/unlock': typeof UnlockRoute
  '/advances': typeof AppAdvancesRoute
  '/attendance': typeof AppAttendanceRoute
  '/bonuses': typeof AppBonusesRoute
  '/employees': typeof AppEmployeesRoute
  '/incentives': typeof AppIncentivesRoute
  '/payroll': typeof AppPayrollRoute
  '/penalties': typeof AppPenaltiesRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/unlock': typeof UnlockRoute
  '/_app/advances': typeof AppAdvancesRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/bonuses': typeof AppBonusesRoute
  '/_app/employees': typeof AppEmployeesRoute
  '/_app/incentives': typeof AppIncentivesRoute
  '/_app/payroll': typeof AppPayrollRoute
  '/_app/penalties': typeof AppPenaltiesRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/unlock'
    | '/advances'
    | '/attendance'
    | '/bonuses'
    | '/employees'
    | '/incentives'
    | '/payroll'
    | '/penalties'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/unlock'
    | '/advances'
    | '/attendance'
    | '/bonuses'
    | '/employees'
    | '/incentives'
    | '/payroll'
    | '/penalties'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/unlock'
    | '/_app/advances'
    | '/_app/attendance'
    | '/_app/bonuses'
    | '/_app/employees'
    | '/_app/incentives'
    | '/_app/payroll'
    | '/_app/penalties'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  UnlockRoute: typeof UnlockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/penalties': {
      id: '/_app/penalties'
      path: '/penalties'
      fullPath: '/penalties'
      preLoaderRoute: typeof AppPenaltiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payroll': {
      id: '/_app/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AppPayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/incentives': {
      id: '/_app/incentives'
      path: '/incentives'
      fullPath: '/incentives'
      preLoaderRoute: typeof AppIncentivesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees': {
      id: '/_app/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bonuses': {
      id: '/_app/bonuses'
      path: '/bonuses'
      fullPath: '/bonuses'
      preLoaderRoute: typeof AppBonusesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/advances': {
      id: '/_app/advances'
      path: '/advances'
      fullPath: '/advances'
      preLoaderRoute: typeof AppAdvancesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdvancesRoute: typeof AppAdvancesRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppBonusesRoute: typeof AppBonusesRoute
  AppEmployeesRoute: typeof AppEmployeesRoute
  AppIncentivesRoute: typeof AppIncentivesRoute
  AppPayrollRoute: typeof AppPayrollRoute
  AppPenaltiesRoute: typeof AppPenaltiesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdvancesRoute: AppAdvancesRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppBonusesRoute: AppBonusesRoute,
  AppEmployeesRoute: AppEmployeesRoute,
  AppIncentivesRoute: AppIncentivesRoute,
  AppPayrollRoute: AppPayrollRoute,
  AppPenaltiesRoute: AppPenaltiesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  UnlockRoute: UnlockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
